package org.wcci.apimastery;

import javax.swing.text.html.HTML.Tag;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.wcci.apimastery.experiments.Experiment;
import org.wcci.apimastery.experiments.ExperimentStorage;
import org.wcci.apimastery.inventors.Inventor;
import org.wcci.apimastery.inventors.InventorStorage;

@Component
public class Populator implements CommandLineRunner{

	@Autowired
	ExperimentStorage experimentStorage;
	
	@Autowired
	InventorStorage inventorStorage;

	@Override
	public void run(String... args) throws Exception {
		
		Inventor faraday = new Inventor("Michael Faraday", "England");
		Inventor volta = new Inventor("Alessandro Volta", "Italy");
		Inventor galvani = new Inventor("Luigi Galvani", "Italy");
		inventorStorage.addInventor(faraday);
		inventorStorage.addInventor(volta);
		inventorStorage.addInventor(galvani);
		
		Experiment faradayCage = new Experiment("Faraday Cage", 
												"In 1836, Michael Faraday built a room coated with metal foil and allowed high-voltage discharges from an electrostatic generator to strike the outside of the room.", 
												faraday);
		Experiment magFieldInd = new Experiment("Magnetic Field Induction",
												"Faraday hypothesized that a changing magnetic field is necessary to induce a current in a nearby circuit. To test this, he coiled a wire around a paper cylinder. He connected the coil to a galvanometer, then moved a magnet in and out of the cylinder.", 
												faraday);
		Experiment gobletOfBrine = new Experiment("Goblet of Brine", 
												  "Initially he experimented with individual cells in series, each cell being a wine goblet filled with brine into which the two dissimilar electrodes were dipped. The voltaic pile replaced the goblets with cardboard soaked in brine.", 
												  volta);
		Experiment frogLegs = new Experiment("The Frog Leg and the Scalpel",
											 "The beginning of Galvani's experiments with bioelectricity has a popular legend which says that the Galvani was slowly skinning a frog at a table where he and his wife had been conducting experiments with static electricity by rubbing frog skin. Galvani's assistant touched an exposed sciatic nerve of the frog with a metal scalpel that had picked up a charge. At that moment, they saw sparks and the dead frog's leg kicked as if in life. The observation made the Galvanis the first investigators to appreciate the relationship between electricity and animation—or life. This finding provided the basis for the new understanding that the impetus behind muscle movement was electrical energy carried by a liquid (ions), and not air or fluid as in earlier balloonist theories. Galvani coined the term animal electricity to describe the force that activated the muscles of his specimens. Along with contemporaries, he regarded their activation as being generated by an electrical fluid that is carried to the muscles by the nerves. The phenomenon was dubbed galvanism, after Galvani and his wife, on the suggestion of his peer and sometime intellectual adversary Alessandro Volta. Galvanis are properly credited with the discovery of bioelectricity. Today, the study of galvanic effects in biology is called electrophysiology, the term galvanism being used only in historical contexts.",
											 galvani);
		
		experimentStorage.addExperiment(faradayCage);
		experimentStorage.addExperiment(magFieldInd);
		experimentStorage.addExperiment(gobletOfBrine);
		experimentStorage.addExperiment(frogLegs);
	}
}
